-- Create jarvis_feedback table if it doesn't exist
create table if not exists jarvis_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text not null,
  type text not null, -- 'bug', 'feature', 'other'
  path text,
  user_agent text,
  status text default 'open' -- 'open', 'in_progress', 'resolved'
);

-- Enable Row Level Security (RLS)
alter table jarvis_feedback enable row level security;

-- Policy: Allow anyone to insert (public feedback)
create policy "Allow public insert"
  on jarvis_feedback for insert
  with check (true);

-- Policy: Allow admins to read/update (Assuming basic authenticated read for now, typically would be admin-only)
-- For simplicity in this fix, we allow authenticated users (which includes admins) to read.
create policy "Allow authenticated read"
  on jarvis_feedback for select
  using (auth.role() = 'authenticated');

create policy "Allow authenticated update"
  on jarvis_feedback for update
  using (auth.role() = 'authenticated');
